### ISSUE TITLE
[ERROR] "Two documentclass or documentstyle" 

### ISSUE THREAD

**Issue by slantingsun** [Ravby/eswa-template#5]
33: Two \documentclass or \documentstyle commands. \documentclass[review]{
: destination with the same identifier (name{page.1}) has been already used, duplicate ignored<to be read again> \relax l.125 \item \textbf {Author names and affiliations.} Where the family nam...

**Comment by Ravby** [comment]
Fixed in 9ae9bdc43ab05eb710ec994154a09baa9f70e19c
